### Create contact 1
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Kelsie",
  "lastName": "Garcia",
  "email": "kelsie@example.com",
  "favoriteColor": "Green",
  "birthday": "1996-04-15"
}

### Create contact 2
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Avery",
  "lastName": "Kim",
  "email": "avery@example.com",
  "favoriteColor": "Blue",
  "birthday": "1995-10-03"
}

### Create contact 3
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Noah",
  "lastName": "Lee",
  "email": "noah@example.com",
  "favoriteColor": "Purple",
  "birthday": "1997-02-20"
}

### Get all contacts
GET http://localhost:8080/contacts


